updated the comments api request
Lambda-School-Labs/human-rights-first-asylum-be-a pull request #134
Opened 2021-06-14 23:03 UTC by lizapincsak

## Description
Juan and I added a put request to edit the case comment from 'Null' to whatever the admin types in. We added a put request in caseRouter and updateComment in the caseModel. We then updated the README.md documentation for this route.

Fixes # (issue)
Allows FE to update comment status from Null to a new comment. 

## Type of change
Added a new BE endpoint for the FE to access.

Please delete options that are not relevant.
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] No duplicate code left within changed files
- [ ] Size of pull request kept to a minimum
- [ ] Pull request description clearly describes changes made & motivations for said changes

2021-06-14 23:44 UTC, Poonchy requested changes
Test with the update instead of updateComment function. If it works, I recommend removing updateComment. Other than that, routing and readme looks good.

2021-06-14 23:44 UTC, Poonchy commented on api/cases/caseModel.js
> +
Might not be necessary. Test locally with the update function.

2021-06-15 00:16 UTC, juancaruizc approved these changes
Awesome job Liza!

2021-06-15 20:47 UTC, Poonchy approved these changes
Looks good to me now. Clean and simple 👍🏻

2021-06-15 20:47 UTC, merged