Feature/roles db/rpeck cnev bmill
Lambda-School-Labs/human-rights-first-asylum-be-a pull request #152
Opened 2021-07-13 23:27 UTC by andromedis

## Description

#### Changes:

- Added migration and seed to create roles table in the database
- Edited migration and seed for profiles table, removed roles column and added role_id foreign key column
- Edited profile seed to have a moderator user for testing
- Reordered seed files and roles migration to ensure they run in the correct order
- Updated find functions in profileModel to join with roles table and return role_name of profiles
- Updated reference profile schema in documentation

#### Goal/Context: 

- Better database normalization
- Upcoming changes to how role permissions are handled to fix security vulnerability
- Upcoming addition of moderator role with case review permissions
- Needed more consistent way to reference roles

#### Fixes:

- Lack of database normalization around profile roles

## Type of change

- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

2021-07-14 15:09 UTC, kmcervan reviewed
I have nothing to add, I think it's good.

2021-07-14 19:01 UTC, bukit3point0 requested changes
Everything is clean; I've requested in comments to review other files for consistency of selecting all queries and cleaning up unnecessary comments. Otherwise, looks good to me!

2021-07-14 19:01 UTC, bukit3point0 commented on api/profile/profileModel.js
> +    .select('*');
The `.select('*')` line is generally unnecessary when selecting all from all tables queried. It's in very few places in the repo, but since it's in place in other locations, can you double check that it's consistent throughout?

2021-07-14 19:01 UTC, bukit3point0 commented on data/seeds/001-role.js
> +      // Inserts seed entries
The comments on this file are unnecessary; please remove them

2021-07-14 21:40 UTC, andromedis commented
Tried to remove new commits that belonged in a separate PR, ended up with other people's commits from a month ago! Help

2021-07-14 22:29 UTC, ryan-hamblin commented on api/cases/caseRouter.js
> +router.put('/comment', (req, res) => {
I'm curious about the naming convention of this endpoint. I thought we were changing 'cases' and this references comments. 

Do you have any background for me as to why this was done this way?

2021-07-14 22:31 UTC, ryan-hamblin commented on api/profile/profileModel.js
> +    .select('*');
+1 I'd love to know more about the need for the `.select('*')`. This might be a good time to clean things up holistically.

2021-07-14 22:37 UTC, ryan-hamblin commented on data/seeds/002-profiles.js
>  const profiles = [...new Array(9)].map((i, idx) => ({
There's probably a more semantic variables we can use in lieu of `i` and `idx`. `i` in this case is the element (object or item at that location in the array) and `idx` is the index at that index.

2021-07-15 17:26 UTC, andromedis commented on api/profile/profileModel.js
> +    .select('*');
This PR got messed up with commits from the last labs team that shouldn't be on the PR. I made a new PR after manually adding all the changes that should be there to a new branch. There, I made and edit to remove like 26, it was indeed unnecessary.

2021-07-15 17:28 UTC, andromedis commented on api/profile/profileModel.js
> +    .select('*');
New PR: https://github.com/Lambda-School-Labs/human-rights-first-asylum-be-a/pull/153

2021-07-15 17:29 UTC, andromedis commented on data/seeds/001-role.js
> +      // Inserts seed entries
Comments removed in new PR with only commits made by the team: https://github.com/Lambda-School-Labs/human-rights-first-asylum-be-a/pull/153

2021-07-15 17:30 UTC, andromedis commented on api/cases/caseRouter.js
> +router.put('/comment', (req, res) => {
This change was made by another team in commits that should have never ended up in this PR, they are not included in the new PR: https://github.com/Lambda-School-Labs/human-rights-first-asylum-be-a/pull/153

2021-07-15 17:30 UTC, andromedis commented on data/seeds/002-profiles.js
>  const profiles = [...new Array(9)].map((i, idx) => ({
I found this part of the code confusing also, but was not attempting to do a refactor of all the seeds, just to add new data.

2021-07-15 17:31 UTC, andromedis commented
New PR here to remove commits from the last team that shouldn't have appeared here: https://github.com/Lambda-School-Labs/human-rights-first-asylum-be-a/pull/153

2021-07-15 17:34 UTC, closed without merging