Built database of approved cases - Created route for FE to view all approved cases. Release #1
Lambda-School-Labs/human-rights-first-asylum-be-a pull request #45
Opened 2021-02-19 07:41 UTC by sebass482

- addition of new migration 'approved-cases'
- new findAllAproved method in the caseMode file
- caseRouter edited to now include a route for FE to see all admin-approved cases.

2021-02-23 07:00 UTC, saharj approved these changes
Please remember to fix lint errors on `api/cases/caseRouter.js`

2021-02-23 07:04 UTC, saharj requested changes

2021-02-23 07:04 UTC, saharj commented on data/migrations/20210215211259_approved-cases.js
> +    return knex.schema.dropTableIfExists('cases');
You are calling your table `approved-cases`, and this string should reflect that

2021-02-24 17:38 UTC, babeytapratt approved these changes
The database looks very good and is ready to have approved cases populated.

2021-03-01 07:18 UTC, saharj approved these changes

2021-03-01 07:18 UTC, merged