Updated mock seed data to reflect changes agreed upon by DS, FE, and BE
Lambda-School-Labs/human-rights-first-asylum-be-a pull request #54
Opened 2021-03-16 20:20 UTC by MattBokovitz1

Updated mock seed data fields to match Data Science's schema.

2021-03-16 20:25 UTC, odst0016 requested changes
Looks like one of the changes wasn't made.

2021-03-16 20:25 UTC, odst0016 commented on data/seeds/003-cases.js
>            judge_name: 'Charles K. Adkins-Blanch',
I cant find the change to judge in this one.

2021-03-16 20:27 UTC, kristapants reviewed
One comment left inline for a boolean that may need to be a string.

2021-03-16 20:27 UTC, kristapants commented on data/seeds/003-cases.js
> +          protected_ground: true,
This true should be a string, I think.

2021-03-16 22:09 UTC, MattBokovitz1 commented on data/seeds/003-cases.js
> +          protected_ground: true,
Thanks for pointing this out, I fixed this.

2021-03-16 22:10 UTC, MattBokovitz1 commented on data/seeds/003-cases.js
>            judge_name: 'Charles K. Adkins-Blanch',
Thanks for point this out, I changed this and made a new commit.

2021-03-16 22:30 UTC, odst0016 approved these changes

2021-03-17 15:41 UTC, kristapants approved these changes
These changes match with the changes I've made to the table builder. This should bring us into line across BE and DS

2021-03-17 15:41 UTC, merged