implemented update and deleting users for okta as well as our database
Lambda-School-Labs/human-rights-first-asylum-be-a pull request #75
Opened 2021-04-23 00:24 UTC by reesharper

2021-04-23 00:35 UTC, c-melchor approved these changes
Nice code, looks clean and well written. This will be a great addition to the workflow of the app.

2021-04-23 18:47 UTC, ndossett approved these changes

2021-04-23 18:47 UTC, ndossett commented on data/migrations/20200625220949_create-profile.js
> +      table.string('firstName');
I'm glad you had the thought to separate the name out - should be much easier for functionality in many other components as well.

2021-04-23 21:00 UTC, crystal-csete approved these changes
This is a great fix, now the front end and back end can talk correctly.

2021-04-23 22:52 UTC, JusticeMatthew requested changes
Looks like this branch is a bit behind main, can you update it then resubmit your pull please and thank you!

2021-04-24 02:09 UTC, JusticeMatthew approved these changes

2021-04-24 02:10 UTC, merged